[workspace]
authors = ["Erik Holum <eholum@gmail.com>"]
channels = ["conda-forge"]
name = "roboplan-ros"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
setup-colcon = { cmd = """
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true && \
colcon mixin update default
""" }
build = { cmd = ["colcon", "build"] }
build-symlink = { cmd = ["colcon", "build", "--symlink-install"] }
test = { cmd = [
  "colcon",
  "test",
]}
test-result = {cmd = [
  "colcon",
  "test-result",
  "--verbose",
]}

[dependencies]
# Build deps
colcon-common-extensions = ">=0.3.0,<0.4"
colcon-mixin = ">=0.2.3,<0.3"
cmake = ">=3.30.5,<4"
clangxx = ">=19.1.7,<20"
lld = ">=19.1.2,<20"
ninja = ">=1.13.1,<2"
mold = ">=2.40.2,<3"
sccache = ">=0.10.0,<0.11"

# Common roboplan base deps
python = ">=3.11,<3.13"
gtest = ">=1.17.0,<2"
viser = ">=1.0.21,<1.0.25"
tyro = ">=0.9.32,<0.10"
matplotlib = ">=3.10.6,<4"
filelock = ">=3.20.0,<4"
numpy = ">=1.26.4,<3"
nanobind = ">=2.12.0,<3"
libtoppra  = ">=0.6.4,<0.7"
osqp-eigen = ">=0.11.0,<0.12"

# For ROS, should be available across distros
lttng-ust = ">=2.13.9,<3"

[pypi-dependencies]
pycollada = ">=0.9.2, <0.10"

# For viser
nodeenv = ">=1.9.1"

[activation.env]
# Prioritize pixi installed packages
CMAKE_PREFIX_PATH = "${CONDA_PREFIX}:${CMAKE_PREFIX_PATH}"
# Ensures the linker knows where to look for conda managed packages
LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LIBRARY_PATH}"
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
LDFLAGS = "-L${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib"
CXXFLAGS = "-fuse-ld=mold"

[feature.kilted]
channels = ["https://prefix.dev/robostack-kilted"]

[feature.kilted.dependencies]
ros-kilted-ros-base = "*"

# RoboPlan and RoboPlan ROS dependencies
ros-kilted-builtin-interfaces = "*"
ros-kilted-coal = "*"
ros-kilted-console-bridge-vendor = "*"
ros-kilted-controller-manager = "*"
ros-kilted-eigenpy = "*"
ros-kilted-geometry-msgs = "*"
ros-kilted-interactive-markers = "*"
ros-kilted-joint-state-broadcaster = "*"
ros-kilted-joint-trajectory-controller = "*"
ros-kilted-pinocchio = "*"
ros-kilted-robot-state-publisher = "*"
ros-kilted-rviz2 = "*"
ros-kilted-sensor-msgs = "*"
ros-kilted-tf2-eigen = "*"
ros-kilted-tinyxml2-vendor = "*"
ros-kilted-tl-expected = "*"
ros-kilted-topic-tools = "*"
ros-kilted-trajectory-msgs = "*"
ros-kilted-urdfdom = "*"
ros-kilted-visualization-msgs = "*"
ros-kilted-xacro = "*"
ros-kilted-yaml-cpp-vendor = "*"

[feature.kilted.activation.env]
ROS_DISTRO = "kilted"

[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros-base = "*"

# RoboPlan and RoboPlan ROS dependencies
ros-jazzy-builtin-interfaces = "*"
ros-jazzy-coal = "*"
ros-jazzy-console-bridge-vendor = "*"
ros-jazzy-controller-manager = "*"
ros-jazzy-eigenpy = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-interactive-markers = "*"
ros-jazzy-joint-state-broadcaster = "*"
ros-jazzy-joint-trajectory-controller = "*"
ros-jazzy-pinocchio = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-tf2-eigen = "*"
ros-jazzy-tinyxml2-vendor = "*"
ros-jazzy-tl-expected = "*"
ros-jazzy-topic-tools = "*"
ros-jazzy-trajectory-msgs = "*"
ros-jazzy-urdfdom = "*"
ros-jazzy-visualization-msgs = "*"
ros-jazzy-xacro = "*"
ros-jazzy-yaml-cpp-vendor = "*"

[feature.jazzy.activation.env]
ROS_DISTRO = "jazzy"

[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-ros-base = "*"

# RoboPlan and RoboPlan ROS dependencies
ros-humble-builtin-interfaces = "*"
ros-humble-coal = "*"
ros-humble-console-bridge-vendor = "*"
ros-humble-controller-manager = "*"
ros-humble-eigenpy = "*"
ros-humble-geometry-msgs = "*"
ros-humble-interactive-markers = "*"
ros-humble-joint-state-broadcaster = "*"
ros-humble-joint-trajectory-controller = "*"
ros-humble-pinocchio = "*"
ros-humble-robot-state-publisher = "*"
ros-humble-rviz2 = "*"
ros-humble-sensor-msgs = "*"
ros-humble-tf2-eigen = "*"
ros-humble-tinyxml2-vendor = "*"
ros-humble-tl-expected = "*"
ros-humble-topic-tools = "*"
ros-humble-trajectory-msgs = "*"
ros-humble-urdfdom = "*"
ros-humble-visualization-msgs = "*"
ros-humble-xacro = "*"
ros-humble-yaml-cpp-vendor = "*"

[feature.humble.activation.env]
ROS_DISTRO = "humble"

[environments]
kilted = { features = ["kilted"] }
jazzy = { features = ["jazzy"] }
humble = { features = ["humble"] }
