[workspace]
authors = ["Erik Holum <eholum@gmail.com>"]
channels = ["conda-forge"]
name = "roboplan-ros"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"
# For the pixi-build-ros backend
preview = ["pixi-build"]

[tasks]
setup-colcon = { cmd = """
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true && \
colcon mixin update default
""" }
build = { cmd = ["colcon", "build"] }
test = { cmd = [
  "colcon",
  "test",
  "--packages-skip",
  "toppra",
]}
test-result = {cmd = [
  "colcon",
  "test-result",
  "--verbose",
]}

[dependencies]
# Build deps
colcon-common-extensions = ">=0.3.0,<0.4"
colcon-mixin = ">=0.2.3,<0.3"
cmake = ">=3.30.5,<4"
clangxx = ">=19.1.7,<20"
lld = ">=19.1.2,<20"
ninja = ">=1.13.1,<2"
mold = ">=2.40.2,<3"
sccache = ">=0.10.0,<0.11"

# Common roboplan base deps
python = ">=3.11,<3.13"
gtest = ">=1.17.0,<2"
viser = ">=1.0.11,<2"
tyro = ">=0.9.32,<0.10"
matplotlib = ">=3.10.6,<4"
filelock = ">=3.20.0,<4"
# We should install nanobind from pip rather than apt/rosdep
nanobind = ">=2.8.0,<3"
numpy = ">=1.26.4,<3"

# For ROS, should be available across distros
lttng-ust = ">=2.13.9,<3"
# Ensure compatible versions for TOPP-RA deps
pybind11 = ">=3.0.2,<4"
eigen = ">=3.4.0,<4"

[pypi-dependencies]
pycollada = ">=0.9.2, <0.10"

# For viser
nodeenv = ">=1.9.1"

[activation.env]
# Prioritize pixi installed packages
CMAKE_PREFIX_PATH = "${CONDA_PREFIX}:${CMAKE_PREFIX_PATH}"
# Ensures the linker knows where to look for conda managed packages
LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LIBRARY_PATH}"
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
LDFLAGS = "-L${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib"
CXXFLAGS = "-fuse-ld=mold"

[feature.kilted]
channels = ["https://prefix.dev/robostack-kilted"]

[feature.kilted.dependencies]
ros-kilted-ros-base = "*"

[feature.kilted.activation.env]
ROS_DISTRO = "kilted"

[feature.kilted.dev]
# Add path dependencies to the package.xmls in the workspace
ros-kilted-roboplan-ros-cpp = { path = "./roboplan_ros_cpp/package.xml" }
ros-kilted-roboplan-ros-py = { path = "./roboplan_ros_py/package.xml" }
ros-kilted-roboplan-ros-visualization = { path = "./roboplan_ros_visualization/package.xml" }
ros-kilted-roboplan-ros-franka = { path = "./roboplan_ros_examples/roboplan_ros_franka/package.xml" }

# TODO: Once roboplan is stable enough we could just install those packages from Conda
ros-kilted-roboplan-toppra = { path = "./roboplan/roboplan_toppra/package.xml" }
ros-kilted-roboplan-bindings = { path = "./roboplan/bindings/package.xml" }
ros-kilted-roboplan-examples = { path = "./roboplan/roboplan_examples/package.xml" }
ros-kilted-toppra = { path = "./roboplan/external/toppra/cpp/package.xml" }
ros-kilted-roboplan = { path = "./roboplan/roboplan/package.xml" }
ros-kilted-roboplan-oink = { path = "./roboplan/roboplan_oink/package.xml" }
ros-kilted-roboplan-example-models = { path = "./roboplan/roboplan_example_models/package.xml" }
ros-kilted-roboplan-rrt = { path = "./roboplan/roboplan_rrt/package.xml" }
ros-kilted-roboplan-simple-ik = { path = "./roboplan/roboplan_simple_ik/package.xml" }

[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-ros-base = "*"

[feature.jazzy.activation.env]
ROS_DISTRO = "jazzy"

[feature.jazzy.dev]
# Add path dependencies to the package.xmls in the workspace
ros-jazzy-roboplan-ros-cpp = { path = "./roboplan_ros_cpp/package.xml" }
ros-jazzy-roboplan-ros-py = { path = "./roboplan_ros_py/package.xml" }
ros-jazzy-roboplan-ros-visualization = { path = "./roboplan_ros_visualization/package.xml" }
ros-jazzy-roboplan-ros-franka = { path = "./roboplan_ros_examples/roboplan_ros_franka/package.xml" }

# TODO: Once roboplan is stable enough we could just install those packages from Conda
ros-jazzy-roboplan-toppra = { path = "./roboplan/roboplan_toppra/package.xml" }
ros-jazzy-roboplan-bindings = { path = "./roboplan/bindings/package.xml" }
ros-jazzy-roboplan-examples = { path = "./roboplan/roboplan_examples/package.xml" }
ros-jazzy-toppra = { path = "./roboplan/external/toppra/cpp/package.xml" }
ros-jazzy-roboplan = { path = "./roboplan/roboplan/package.xml" }
ros-jazzy-roboplan-oink = { path = "./roboplan/roboplan_oink/package.xml" }
ros-jazzy-roboplan-example-models = { path = "./roboplan/roboplan_example_models/package.xml" }
ros-jazzy-roboplan-rrt = { path = "./roboplan/roboplan_rrt/package.xml" }
ros-jazzy-roboplan-simple-ik = { path = "./roboplan/roboplan_simple_ik/package.xml" }

[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-ros-base = "*"

[feature.humble.activation.env]
ROS_DISTRO = "humble"

[feature.humble.dev]
# Add path dependencies to the package.xmls in the workspace
ros-humble-roboplan-ros-cpp = { path = "./roboplan_ros_cpp/package.xml" }
ros-humble-roboplan-ros-py = { path = "./roboplan_ros_py/package.xml" }
ros-humble-roboplan-ros-visualization = { path = "./roboplan_ros_visualization/package.xml" }
ros-humble-roboplan-ros-franka = { path = "./roboplan_ros_examples/roboplan_ros_franka/package.xml" }

# # TODO: Once roboplan is stable enough we could just install those packages from Conda
ros-humble-roboplan-toppra = { path = "./roboplan/roboplan_toppra/package.xml" }
ros-humble-roboplan-bindings = { path = "./roboplan/bindings/package.xml" }
ros-humble-roboplan-examples = { path = "./roboplan/roboplan_examples/package.xml" }
ros-humble-toppra = { path = "./roboplan/external/toppra/cpp/package.xml" }
ros-humble-roboplan = { path = "./roboplan/roboplan/package.xml" }
ros-humble-roboplan-oink = { path = "./roboplan/roboplan_oink/package.xml" }
ros-humble-roboplan-example-models = { path = "./roboplan/roboplan_example_models/package.xml" }
ros-humble-roboplan-rrt = { path = "./roboplan/roboplan_rrt/package.xml" }
ros-humble-roboplan-simple-ik = { path = "./roboplan/roboplan_simple_ik/package.xml" }

[environments]
kilted = { features = ["kilted"] }
jazzy = { features = ["jazzy"] }
humble = { features = ["humble"] }
