ARG ROS_DISTRO=jazzy

# Preserve rosdep installs separate from source. Maintains caches as long as rosdeps do not change.
FROM alpine:latest AS package-manifests

COPY . /roboplan_ros
RUN find /roboplan_ros -type f ! -name "package.xml" ! -name "COLCON_IGNORE" -delete && \
    find /roboplan_ros -type d -empty -delete

FROM ros:${ROS_DISTRO} AS roboplan_ros

ENV PIP_BREAK_SYSTEM_PACKAGES=1
SHELL ["/bin/bash", "-c"]

# Install core dependencies.
RUN apt update -y \
    && apt upgrade -y \
    && apt install -y libgmock-dev python3-pip

# Install Python dependencies needed for bindings.
# Note that since Pinocchio in ROS is built with Numpy 1.x, we must preserve this by
# pinning a bunch of other versions. These pins are ROS specific, and at odds with
# non-ROS workflows, so we cannot put these as requirements in the `pyproject.toml`.
# As/if this package matures, a possible solution is to apply patches for ROS release.
RUN pip3 install \
        nanobind \
        matplotlib \
        "numpy<2.0.0" \
        opencv-contrib-python-headless \
        typing_extensions==4.10.0 \
        tyro \
        "viser>=1.0.1"

# Create a ROS 2 workspace and copy in the source code.
RUN mkdir -p /workspace/roboplan_ws/src/roboplan_ros
WORKDIR /workspace/roboplan_ws

# Copy package manifests for installing rosdeps
COPY --from=package-manifests /roboplan_ros ./src/roboplan_ros
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && rosdep install --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y

# Copy in remaining source and build
COPY . src/roboplan_ros
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
    && colcon build --cmake-args -DBUILD_TESTING=ON

# Set up entrypoint and working folder.
WORKDIR /workspace/roboplan_ws
COPY ./.docker/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
RUN echo "source /entrypoint.sh" >> ~/.bashrc
